const tests = [
  // Estudios Individuales
  { id: "TRI-001", name: "TRIAGE CARDIACO DE TRES PARAMETROS", category: "CARDIACO", price: 2131.04, description: "" },
  { id: "CAR-001", name: "BNP", category: "CARDIACO", price: 1599.00, description: "" },
  { id: "CAR-002", name: "MIOGLOBINA", category: "CARDIACO", price: 1409.00, description: "" },
  { id: "CAR-003", name: "TROPONINA", category: "CARDIACO", price: 1409.00, description: "" },
  { id: "CAR-004", name: "DIMERO D", category: "CARDIACO", price: 1272.00, description: "" },
  { id: "DIV-001", name: "CITOQUIMICO DE L.C.R", category: "DIVERSOS", price: 417.78, description: "" },
  { id: "DIV-002", name: "CITOQUIMICO DE LIQUIDO SINOVIAL", category: "DIVERSOS", price: 417.78, description: "" },
  { id: "DIV-003", name: "CITOQUIMICO DE LIQUIDO PLEURAL", category: "DIVERSOS", price: 417.78, description: "" },
  { id: "DIV-004", name: "CITOQUIMICO DE LIQUIDO ASCITICO", category: "DIVERSOS", price: 417.78, description: "" },
  { id: "DIV-005", name: "PROCALCITONINA", category: "DIVERSOS", price: 1170.00, description: "" },
  { id: "DIV-006", name: "GASOMETRIA VENOSA", category: "DIVERSOS", price: 586.61, description: "" },
  { id: "DIV-007", name: "GASOMETRIA ARTERIAL", category: "DIVERSOS", price: 1056.00, description: "" },
  { id: "DIV-008", name: "HLA B27", category: "DIVERSOS", price: 1695.99, description: "" },
  { id: "DIV-009", name: "LEPTOSPIRA", category: "DIVERSOS", price: 1952.28, description: "" },
  { id: "DIV-010", name: "CITOLOGICO", category: "DIVERSOS", price: 343.00, description: "" },
  { id: "DIV-011", name: "AMONIO", category: "DIVERSOS", price: 522.00, description: "" },
  { id: "DIV-012", name: "DHEA-S", category: "DIVERSOS", price: 439.74, description: "" },
  { id: "DIV-013", name: "ANTICOAGULANTE LUPICO", category: "DIVERSOS", price: 821.28, description: "" },
  { id: "DIV-014", name: "CADENAS KAPPA Y LAMBDA", category: "DIVERSOS", price: 797.46, description: "" },
  { id: "DIV-015", name: "INMUNO FENOTIPO COMPLETO LEUCENIA AGUDA", category: "DIVERSOS", price: 8343.50, description: "" },
  { id: "DIV-016", name: "INMUNO FENOTIPO LINFOMAS Y LEUCEMIA CRONICA", category: "DIVERSOS", price: 5443.00, description: "" },
  { id: "DIV-017", name: "INMUNO FENOTIPO MIELOMA", category: "DIVERSOS", price: 2750.00, description: "" },
  { id: "HEM-001", name: "BIOMETRIA HEMATICA", category: "HEMATOLOGIA Y COAGULACION", price: 222.00, description: "" },
  { id: "HEM-004", name: "CELULAS L.E.", category: "HEMATOLOGIA Y COAGULACION", price: 110.00, description: "" },
  { id: "HEM-005", name: "EOSINOFILOS EN MOCO NASAL", category: "HEMATOLOGIA Y COAGULACION", price: 60.00, description: "" },
  { id: "HEM-006", name: "COOMBS DIRECTO", category: "HEMATOLOGIA Y COAGULACION", price: 95.00, description: "" },
  { id: "HEM-007", name: "COOMBS INDIRECTO", category: "HEMATOLOGIA Y COAGULACION", price: 95.00, description: "" },
  { id: "HEM-008", name: "CUENTA DE PLAQUETAS", category: "HEMATOLOGIA Y COAGULACION", price: 70.00, description: "" },
  { id: "HEM-009", name: "CUENTA DE RETICULOCITOS", category: "HEMATOLOGIA Y COAGULACION", price: 94.00, description: "" },
  { id: "HEM-010", name: "ERITROSEDIMENTACION (VSG)", category: "HEMATOLOGIA Y COAGULACION", price: 94.00, description: "" },
  { id: "COG-003", name: "FIBRINOGENO", category: "HEMATOLOGIA Y COAGULACION", price: 241.00, description: "" },
  { id: "HEM-002", name: "GRUPO SANGUINEO Y FACTOR RH", category: "HEMATOLOGIA Y COAGULACION", price: 127.00, description: "" },
  { id: "HEM-011", name: "HIERRO SERICO", category: "HEMATOLOGIA Y COAGULACION", price: 290.00, description: "" },
  { id: "HEM-012", name: "CAPACIDAD DE FIJACION DE HIERRO", category: "HEMATOLOGIA Y COAGULACION", price: 435.00, description: "" },
  { id: "HEM-013", name: "PLASMODIUM", category: "HEMATOLOGIA Y COAGULACION", price: 0.00, description: "" },
  { id: "COG-001", name: "TIEMPO DE PROTROMBINA", category: "HEMATOLOGIA Y COAGULACION", price: 221.00, description: "" },
  { id: "COG-002", name: "TIEMPO DE TROMBINA PARCIAL", category: "HEMATOLOGIA Y COAGULACION", price: 221.00, description: "" },
  { id: "COG-004", name: "TIEMPO DE SANGRADO", category: "HEMATOLOGIA Y COAGULACION", price: 50.00, description: "" },
  { id: "COG-005", name: "TIEMPO DE COAGULACION", category: "HEMATOLOGIA Y COAGULACION", price: 50.00, description: "" },
  { id: "COG-006", name: "TIEMPO DE TROMBINA", category: "HEMATOLOGIA Y COAGULACION", price: 0.00, description: "" },
  { id: "HEM-014", name: "ACIDO FOLICO", category: "HEMATOLOGIA Y COAGULACION", price: 0.00, description: "" },
  { id: "HEM-015", name: "VITAMINA B12", category: "HEMATOLOGIA Y COAGULACION", price: 0.00, description: "" },
  { id: "HEM-003", name: "FROTIS SANGUINEO", category: "HEMATOLOGIA Y COAGULACION", price: 60.00, description: "" },
  { id: "HEM-016", name: "FERRITINA", category: "HEMATOLOGIA Y COAGULACION", price: 570.00, description: "" },
  { id: "HEM-017", name: "INR", category: "HEMATOLOGIA Y COAGULACION", price: 0.00, description: "" },
  { id: "HEM-018", name: "TRANSFERRINA", category: "HEMATOLOGIA Y COAGULACION", price: 0.00, description: "" },
  { id: "HEM-019", name: "EOSINOFILOS EN MOCO NASAL SERIADO", category: "HEMATOLOGIA Y COAGULACION", price: 50.00, description: "" },
  { id: "HOR-010", name: "T3 TOTAL", category: "HORMONAS", price: 167.00, description: "" },
  { id: "HOR-003", name: "T3 LIBRE", category: "HORMONAS", price: 167.00, description: "" },
  { id: "HOR-011", name: "T4 TOTAL", category: "HORMONAS", price: 167.00, description: "" },
  { id: "HOR-002", name: "T4 LIBRE", category: "HORMONAS", price: 167.00, description: "" },
  { id: "HOR-001", name: "TSH-S", category: "HORMONAS", price: 167.00, description: "" },
  { id: "HOR-012", name: "FSH", category: "HORMONAS", price: 160.00, description: "" },
  { id: "HOR-013", name: "LH", category: "HORMONAS", price: 180.00, description: "" },
  { id: "HOR-004", name: "PROLACTINA", category: "HORMONAS", price: 241.00, description: "" },
  { id: "HOR-007", name: "ESTRADIOL", category: "HORMONAS", price: 180.00, description: "" },
  { id: "HOR-014", name: "PROGESTERONA", category: "HORMONAS", price: 180.00, description: "" },
  { id: "HOR-006", name: "TESTOSTERONA LIBRE", category: "HORMONAS", price: 180.00, description: "" },
  { id: "HOR-005", name: "TESTOSTERONA TOTAL", category: "HORMONAS", price: 241.00, description: "" },
  { id: "HOR-008", name: "CORTISOL MATUTINO/VESPERTINO", category: "HORMONAS", price: 260.00, description: "" },
  { id: "HOR-015", name: "CORTISOL EN ORINA", category: "HORMONAS", price: 214.00, description: "" },
  { id: "HOR-009", name: "HORMONA DEL CRECIMIENTO", category: "HORMONAS", price: 0.00, description: "" },
  { id: "HOR-016", name: "ANDROSTENEDIONA", category: "HORMONAS", price: 0.00, description: "" },
  { id: "HOR-017", name: "17 HIDROXI PROGESTERONA", category: "HORMONAS", price: 0.00, description: "" },
  { id: "HOR-018", name: "PARATHORMONA", category: "HORMONAS", price: 0.00, description: "" },
  { id: "HOR-019", name: "HORMONA ADRENOCORTICOTROPA", category: "HORMONAS", price: 783.00, description: "" },
  { id: "HOR-020", name: "INSULINA SERICA", category: "HORMONAS", price: 210.00, description: "" },
  { id: "INM-009", name: "AC. HIV CUANTITATIVO", category: "INMUNOSEROLOGIA", price: 170.00, description: "" },
  { id: "INM-005", name: "AC. HIV CUALITATIVO", category: "INMUNOSEROLOGIA", price: 222.00, description: "" },
  { id: "INM-006", name: "VDRL CUALITATIVO", category: "INMUNOSEROLOGIA", price: 90.00, description: "" },
  { id: "INM-010", name: "REACCIONES FEBRILES", category: "INMUNOSEROLOGIA", price: 136.00, description: "" },
  { id: "INM-001", name: "FACTOR REUMATOIDE CUANTITATIVO", category: "INMUNOSEROLOGIA", price: 150.00, description: "" },
  { id: "INM-011", name: "FACTOR REUMATOIDE CUALITATIVO", category: "INMUNOSEROLOGIA", price: 90.00, description: "" },
  { id: "INM-002", name: "PROTEINA C REACTIVA CUANTITATIVA", category: "INMUNOSEROLOGIA", price: 348.00, description: "" },
  { id: "INM-012", name: "PROTEINA C REACTIVA CUALITATIVA", category: "INMUNOSEROLOGIA", price: 150.00, description: "" },
  { id: "INM-013", name: "PROTEINA C REACTIVA DE ALTA SENSIBILIDAD", category: "INMUNOSEROLOGIA", price: 140.00, description: "" },
  { id: "INM-014", name: "ANTIESTREPTOTISINAS CUANTITATIVA", category: "INMUNOSEROLOGIA", price: 140.00, description: "" },
  { id: "INM-003", name: "ANTIESTREPTOLISINAS CUALITATIVA", category: "INMUNOSEROLOGIA", price: 129.00, description: "" },
  { id: "INM-015", name: "MONONUCLEOSIS INFECCIOSA", category: "INMUNOSEROLOGIA", price: 390.50, description: "" },
  { id: "INM-016", name: "AC VS AG NUCLEAR IGG (CORE)", category: "INMUNOSEROLOGIA", price: 650.00, description: "" },
  { id: "INM-017", name: "AC VS AG NUCLEAR IGM (CORE)", category: "INMUNOSEROLOGIA", price: 650.00, description: "" },
  { id: "INM-018", name: "INMUNOGLOBULINA IGA", category: "INMUNOSEROLOGIA", price: 1183.18, description: "" },
  { id: "INM-019", name: "INMUNOGLOBULINA IGG", category: "INMUNOSEROLOGIA", price: 1183.18, description: "" },
  { id: "INM-020", name: "INMUNOGLOBULINA IGM", category: "INMUNOSEROLOGIA", price: 1183.18, description: "" },
  { id: "INM-021", name: "INMUNOGLOBULINAS IGE", category: "INMUNOSEROLOGIA", price: 400.00, description: "" },
  { id: "INM-022", name: "COMPLEMENTO C3", category: "INMUNOSEROLOGIA", price: 348.00, description: "" },
  { id: "INM-023", name: "COMPLEMENTO C4", category: "INMUNOSEROLOGIA", price: 348.00, description: "" },
  { id: "INM-024", name: "AC.ANTIESPERMATOZOIDES", category: "INMUNOSEROLOGIA", price: 332.00, description: "" },
  { id: "INM-025", name: "AC.ANTITIROIDES", category: "INMUNOSEROLOGIA", price: 1219.20, description: "" },
  { id: "INM-026", name: "AC.ANTIMICROSOMALES-ANTIPEROXIDASA (ANTI-TPO)", category: "INMUNOSEROLOGIA", price: 609.00, description: "" },
  { id: "INM-027", name: "AC. ANTITIROGLOBULINA (ANTI-TG)", category: "INMUNOSEROLOGIA", price: 609.00, description: "" },
  { id: "INM-028", name: "AC. CONTRARECEPTOR DE TSH (TIROTROPINA)", category: "INMUNOSEROLOGIA", price: 3162.50, description: "" },
  { id: "INM-029", name: "AC ANTICARDIOLIPINAS IGG", category: "INMUNOSEROLOGIA", price: 1113.60, description: "" },
  { id: "INM-030", name: "AC ANTICARDIOLIPINAS IGM", category: "INMUNOSEROLOGIA", price: 612.12, description: "" },
  { id: "INM-031", name: "AC. ANTINUCLEARES POR IF", category: "INMUNOSEROLOGIA", price: 1219.20, description: "" },
  { id: "INM-032", name: "AC. ANTI DNA", category: "INMUNOSEROLOGIA", price: 725.00, description: "" },
  { id: "INM-033", name: "AC. SM", category: "INMUNOSEROLOGIA", price: 449.00, description: "" },
  { id: "INM-034", name: "AC.RNP", category: "INMUNOSEROLOGIA", price: 449.00, description: "" },
  { id: "INM-035", name: "AC. SCL-70", category: "INMUNOSEROLOGIA", price: 449.00, description: "" },
  { id: "INM-036", name: "AC. SSA (JO)", category: "INMUNOSEROLOGIA", price: 449.00, description: "" },
  { id: "INM-037", name: "AC.SSB (LA)", category: "INMUNOSEROLOGIA", price: 449.00, description: "" },
  { id: "INM-038", name: "AC. ANTI AMIBA", category: "INMUNOSEROLOGIA", price: 908.60, description: "" },
  { id: "INM-039", name: "AC. ANTI CHLAMYDIA IGG", category: "INMUNOSEROLOGIA", price: 500.00, description: "" },
  { id: "INM-040", name: "AC. ANTI CHLAMYDIA IGM", category: "INMUNOSEROLOGIA", price: 510.00, description: "" },
  { id: "INM-041", name: "AC. ANTI CISTICERCO", category: "INMUNOSEROLOGIA", price: 830.50, description: "" },
  { id: "INM-042", name: "AG. DE GIARDIA EN HECES", category: "INMUNOSEROLOGIA", price: 1348.60, description: "" },
  { id: "INM-007", name: "AC. ANTI HELICOBACTER PYLORI IGG", category: "INMUNOSEROLOGIA", price: 701.80, description: "" },
  { id: "INM-043", name: "AC. ANTI HELICOBACTER PYLORI IGM", category: "INMUNOSEROLOGIA", price: 1608.20, description: "" },
  { id: "INM-044", name: "AC.ANTI TOXOPLASMA IGG", category: "INMUNOSEROLOGIA", price: 620.00, description: "" },
  { id: "INM-045", name: "AC.ANTI TOXOPLASMA IGM", category: "INMUNOSEROLOGIA", price: 620.00, description: "" },
  { id: "INM-046", name: "AC. ANTI CITOMEGALOVIRUS IGG", category: "INMUNOSEROLOGIA", price: 620.00, description: "" },
  { id: "INM-047", name: "AC. ANTI CITOMEGALOVIRUS IGM", category: "INMUNOSEROLOGIA", price: 620.00, description: "" },
  { id: "INM-048", name: "AC. ANTI RUBEOLA IGG", category: "INMUNOSEROLOGIA", price: 620.00, description: "" },
  { id: "INM-049", name: "AC. ANTI RUBEOLA IGM", category: "INMUNOSEROLOGIA", price: 620.00, description: "" },
  { id: "INM-050", name: "PRUEBA DE EMBARAZO EN ORINA", category: "INMUNOSEROLOGIA", price: 100.00, description: "" },
  { id: "INM-008", name: "PRUEBA DE EMBARAZO EN SANGRE", category: "INMUNOSEROLOGIA", price: 156.00, description: "" },
  { id: "INM-051", name: "ESPERMATOBIOSCOPIA DIRECTA", category: "INMUNOSEROLOGIA", price: 160.00, description: "" },
  { id: "INM-052", name: "ROSA DE BENGALA", category: "INMUNOSEROLOGIA", price: 110.00, description: "" },
  { id: "INM-053", name: "2-MERCAPTO-ETANOL (BRUCELLA)", category: "INMUNOSEROLOGIA", price: 330.00, description: "" },
  { id: "INM-054", name: "AC/AG PARA DENGUE", category: "INMUNOSEROLOGIA", price: 690.00, description: "" },
  { id: "INM-055", name: "AC. ANTI HERPES 1 Y 2 IGG", category: "INMUNOSEROLOGIA", price: 300.00, description: "" },
  { id: "INM-056", name: "AC. ANTI HERPES 1 Y 2 IGM", category: "INMUNOSEROLOGIA", price: 310.00, description: "" },
  { id: "INM-057", name: "INFLUENZA A Y B", category: "INMUNOSEROLOGIA", price: 800.00, description: "" },
  { id: "INM-058", name: "AC ANTI BETA 2 GLICOPROTEINAS IGG/IGM", category: "INMUNOSEROLOGIA", price: 1062.00, description: "" },
  { id: "INM-059", name: "CLOSTRIDIUM DIFFICILE", category: "INMUNOSEROLOGIA", price: 2126.30, description: "" },
  { id: "INM-060", name: "AC ANTI PEPTIDOS CITRULINADOS", category: "INMUNOSEROLOGIA", price: 1200.00, description: "" },
  { id: "INM-061", name: "AC ANTI CHIKUNGUNYA IGM", category: "INMUNOSEROLOGIA", price: 400.00, description: "" },
  { id: "INM-062", name: "AC. ANTI ANCA C Y ANCA P", category: "INMUNOSEROLOGIA", price: 2192.30, description: "" },
  { id: "INM-063", name: "AC. ANTI TREPONEMA PALLIDUM", category: "INMUNOSEROLOGIA", price: 100.00, description: "" },
  { id: "INM-064", name: "AC ANTIMEMBRANA BASAL GLOMERULAR", category: "INMUNOSEROLOGIA", price: 2168.00, description: "" },
  { id: "INM-065", name: "TOXOCARA CANNIS IGG E IGM", category: "INMUNOSEROLOGIA", price: 2514.60, description: "" },
  { id: "INM-066", name: "MYCOBACTERIUM TUBERCULOSIS POR PCR", category: "INMUNOSEROLOGIA", price: 4716.80, description: "" },
  { id: "INM-067", name: "VIRUS EPSTEIN BARR", category: "INMUNOSEROLOGIA", price: 4716.80, description: "" },
  { id: "INM-068", name: "AC. ANTI RECEPTORES DE ACETIL COLINA", category: "INMUNOSEROLOGIA", price: 2404.50, description: "" },
  { id: "INM-069", name: "AC. ANTI CHAGAS", category: "INMUNOSEROLOGIA", price: 520.00, description: "" },
  { id: "INM-070", name: "AC.HAV IGM", category: "INMUNOSEROLOGIA", price: 509.76, description: "" },
  { id: "INM-071", name: "AC.HAV TOTAL", category: "INMUNOSEROLOGIA", price: 508.76, description: "" },
  { id: "INM-072", name: "AG SUPERFICIE HEPATITIS B", category: "INMUNOSEROLOGIA", price: 415.00, description: "" },
  { id: "INM-073", name: "AC V.S. AG. NUCLEAR HEP.B IGG", category: "INMUNOSEROLOGIA", price: 450.00, description: "" },
  { id: "INM-074", name: "AC V.S. AG. NUCLEAR HEP.B IGM", category: "INMUNOSEROLOGIA", price: 450.00, description: "" },
  { id: "INM-075", name: "AC VS VIRUS HEP.C TOTAL", category: "INMUNOSEROLOGIA", price: 638.00, description: "" },
  { id: "MAR-004", name: "ALFAFETOPROTEINA (AFP)", category: "MARCADORES TUMORALES", price: 500.00, description: "" },
  { id: "MAR-003", name: "ANTIGENO CARCINOEMBRIONARIO (CEA)", category: "MARCADORES TUMORALES", price: 400.00, description: "" },
  { id: "MAR-005", name: "ANTIGENO CA 15-3 (MAMA)", category: "MARCADORES TUMORALES", price: 744.00, description: "" },
  { id: "MAR-006", name: "ANTIGENO CA 21.1 (PULMON)", category: "MARCADORES TUMORALES", price: 280.00, description: "" },
  { id: "MAR-007", name: "ANTIGENO CA 27.29 (MAMA)", category: "MARCADORES TUMORALES", price: 1551.00, description: "" },
  { id: "MAR-008", name: "ANTIGENO CA 19-9 (PANCREAS)", category: "MARCADORES TUMORALES", price: 430.00, description: "" },
  { id: "MAR-002", name: "ANTIGENO CA 125 (OVARIO)", category: "MARCADORES TUMORALES", price: 400.00, description: "" },
  { id: "MAR-001", name: "ANTIGENO PROSTATICO ESPECIFICO (PSA)", category: "MARCADORES TUMORALES", price: 311.00, description: "" },
  { id: "MAR-009", name: "ANTIGENO PROSTATICO FRACCION LIBRE (PSA FREE)", category: "MARCADORES TUMORALES", price: 478.00, description: "" },
  { id: "MAR-010", name: "CALCITONINA (CA. TIROIDES)", category: "MARCADORES TUMORALES", price: 1136.00, description: "" },
  { id: "MAR-011", name: "GONADOTROPINA CORIONICA HUMANA (GHC)", category: "MARCADORES TUMORALES", price: 362.00, description: "" },
  { id: "MAR-012", name: "CA 72.4 (ESTOMAGO)", category: "MARCADORES TUMORALES", price: 2051.00, description: "" },
  { id: "MIC-022", name: "CULTIVO Y ANTIBIOGRAMA DE EXPECTORACION", category: "MICROBIOLOGIA", price: 350.00, description: "" },
  { id: "MIC-003", name: "CULTIVO Y ANTIBIOGRAMA DIVERSO", category: "MICROBIOLOGIA", price: 350.00, description: "" },
  { id: "MIC-001", name: "CULTIVO Y ANTIBIOGRAMA DE ORINA (UROCULTIVO)", category: "MICROBIOLOGIA", price: 432.00, description: "" },
  { id: "MIC-002", name: "CULTIVO Y ANTIBIOGRAMA DE HECES (COPROCULTIVO)", category: "MICROBIOLOGIA", price: 350.00, description: "" },
  { id: "MIC-006", name: "CULTIVO Y ANTIBIOGRAMA DE LIQUIDOS", category: "MICROBIOLOGIA", price: 580.00, description: "" },
  { id: "MIC-005", name: "HEMOCULTIVO", category: "MICROBIOLOGIA", price: 660.00, description: "" },
  { id: "MIC-007", name: "BAAR (BACILOSCOPIA EN EXPECTORACION) 1MTRA", category: "MICROBIOLOGIA", price: 75.00, description: "" },
  { id: "MIC-008", name: "BAAR (BACILOSCOPIA EN EXPECTORACION) 2MTRA", category: "MICROBIOLOGIA", price: 198.00, description: "" },
  { id: "MIC-009", name: "BAAR (BACILOSCOPIA EN EXPECTORACION) 3 MTRA", category: "MICROBIOLOGIA", price: 308.00, description: "" },
  { id: "MIC-010", name: "BAAR (BACILOSCOPIA EN LIQUIDO) 1MTRA", category: "MICROBIOLOGIA", price: 100.00, description: "" },
  { id: "MIC-011", name: "BAAR (BACILOSCOPIA EN LIQUIDO) 2 MTRA", category: "MICROBIOLOGIA", price: 222.00, description: "" },
  { id: "MIC-012", name: "BAAR (BACILOSCOPIA EN LIQUIDO) 3MTRA", category: "MICROBIOLOGIA", price: 308.00, description: "" },
  { id: "MIC-013", name: "KOH", category: "MICROBIOLOGIA", price: 80.00, description: "" },
  { id: "MIC-014", name: "TINTA CHINA", category: "MICROBIOLOGIA", price: 80.00, description: "" },
  { id: "MIC-004", name: "TICION DE GRAM", category: "MICROBIOLOGIA", price: 80.00, description: "" },
  { id: "MIC-015", name: "CULTIVO DE PUNTA DE CATETER", category: "MICROBIOLOGIA", price: 414.00, description: "" },
  { id: "MIC-016", name: "EXUDADO FARINGEO", category: "MICROBIOLOGIA", price: 365.00, description: "" },
  { id: "MIC-017", name: "CULTIVO EN EXPECTORACION", category: "MICROBIOLOGIA", price: 365.00, description: "" },
  { id: "MIC-018", name: "COPROCULTIVO", category: "MICROBIOLOGIA", price: 365.00, description: "" },
  { id: "MIC-019", name: "CULTIVO TEJIDO", category: "MICROBIOLOGIA", price: 365.00, description: "" },
  { id: "MIC-020", name: "DETECCION RAPIDA DE ESTREPTOCOCOS", category: "MICROBIOLOGIA", price: 414.00, description: "" },
  { id: "MIC-021", name: "CULTIVO DIVERSO", category: "MICROBIOLOGIA", price: 350.00, description: "" },
  { id: "PAR-001", name: "COPROPARASITOSCOPICO 1 MUESTRA", category: "PARASITOLOGIA", price: 65.00, description: "" },
  { id: "PAR-002", name: "COPROPARASITOSCOPICO 2 MUESTRAS", category: "PARASITOLOGIA", price: 80.00, description: "" },
  { id: "PAR-003", name: "COPROPARASITOSCOPICO 3 MUESTRAS", category: "PARASITOLOGIA", price: 95.00, description: "" },
  { id: "PAR-004", name: "COPROLOGICO", category: "PARASITOLOGIA", price: 111.00, description: "" },
  { id: "PAR-005", name: "ROTAVIRUS", category: "PARASITOLOGIA", price: 170.00, description: "" },
  { id: "PAR-006", name: "AMIBA EN FRESCO", category: "PARASITOLOGIA", price: 50.00, description: "" },
  { id: "PAR-007", name: "RASPADO ANAL (OXIUROS)", category: "PARASITOLOGIA", price: 50.00, description: "" },
  { id: "PAR-008", name: "SANGRE OCULTA EN HECES", category: "PARASITOLOGIA", price: 99.00, description: "" },
  { id: "PAR-009", name: "PH Y SUSTANCIAS REDUCTORAS", category: "PARASITOLOGIA", price: 50.00, description: "" },
  { id: "PAR-010", name: "ACCION TRIPTICA EN HECES", category: "PARASITOLOGIA", price: 450.00, description: "" },
  { id: "PAR-011", name: "ANTIGENO HELICOBACTER PYLORI", category: "PARASITOLOGIA", price: 1245.20, description: "" },
  { id: "QUI-007", name: "ACIDO URICO", category: "QUIMICA CLINICA", price: 122.00, description: "" },
  { id: "QUI-015", name: "ALBUMINA", category: "QUIMICA CLINICA", price: 148.00, description: "" },
  { id: "QUI-016", name: "ALDOLASA", category: "QUIMICA CLINICA", price: 0.00, description: "" },
  { id: "QUI-017", name: "ADENOSINA DEAMINASA", category: "QUIMICA CLINICA", price: 0.00, description: "" },
  { id: "QUI-018", name: "ALFA - AMILASA", category: "QUIMICA CLINICA", price: 177.00, description: "" },
  { id: "QUI-012", name: "BILIRRUBINA TOTAL", category: "QUIMICA CLINICA", price: 148.00, description: "" },
  { id: "QUI-013", name: "BILIRRUBINA DIRECTA", category: "QUIMICA CLINICA", price: 148.00, description: "" },
  { id: "QUI-019", name: "CALCIO", category: "QUIMICA CLINICA", price: 148.00, description: "" },
  { id: "QUI-020", name: "CLORO", category: "QUIMICA CLINICA", price: 238.00, description: "" },
  { id: "QUI-003", name: "COLESTEROL TOTAL", category: "QUIMICA CLINICA", price: 122.00, description: "" },
  { id: "QUI-004", name: "COLESTEROL HDL", category: "QUIMICA CLINICA", price: 167.00, description: "" },
  { id: "QUI-005", name: "COLESTEROL LDL", category: "QUIMICA CLINICA", price: 189.00, description: "" },
  { id: "QUI-021", name: "COLINESTERASA", category: "QUIMICA CLINICA", price: 0.00, description: "" },
  { id: "QUI-022", name: "CPK", category: "QUIMICA CLINICA", price: 110.00, description: "" },
  { id: "QUI-023", name: "CPK-MB", category: "QUIMICA CLINICA", price: 230.00, description: "" },
  { id: "QUI-024", name: "CREATININA", category: "QUIMICA CLINICA", price: 119.00, description: "" },
  { id: "QUI-025", name: "CURVA DE TOLERANCIA A LA GLUCOSA (3 TOMAS)", category: "QUIMICA CLINICA", price: 310.00, description: "" },
  { id: "QUI-026", name: "CURVA DE TOLERANCIA A LA GLUCOSA (5 TOMAS)", category: "QUIMICA CLINICA", price: 360.00, description: "" },
  { id: "QUI-011", name: "FOSFATASA ALCALINA", category: "QUIMICA CLINICA", price: 148.00, description: "" },
  { id: "QUI-027", name: "FOSFATASA ACIDA", category: "QUIMICA CLINICA", price: 90.00, description: "" },
  { id: "QUI-028", name: "FRACCION PROSTATICA", category: "QUIMICA CLINICA", price: 0.00, description: "" },
  { id: "QUI-029", name: "FOSFORO", category: "QUIMICA CLINICA", price: 148.00, description: "" },
  { id: "QUI-030", name: "GAMA GLUTAMIL TRANSFERASA", category: "QUIMICA CLINICA", price: 90.00, description: "" },
  { id: "QUI-001", name: "GLUCOSA", category: "QUIMICA CLINICA", price: 119.00, description: "" },
  { id: "QUI-031", name: "GLUCOSA POST-PRANDIAL SIN CARGA", category: "QUIMICA CLINICA", price: 90.00, description: "" },
  { id: "QUI-002", name: "HEMOGLOBINA GLICOSILADA", category: "QUIMICA CLINICA", price: 406.00, description: "" },
  { id: "QUI-032", name: "LACTATO DESHIDROGENASA", category: "QUIMICA CLINICA", price: 148.00, description: "" },
  { id: "QUI-033", name: "LIPASA", category: "QUIMICA CLINICA", price: 235.00, description: "" },
  { id: "QUI-034", name: "LIPIDOS TOTALES", category: "QUIMICA CLINICA", price: 0.00, description: "" },
  { id: "QUI-035", name: "MAGNESIO", category: "QUIMICA CLINICA", price: 148.00, description: "" },
  { id: "QUI-036", name: "POTASIO", category: "QUIMICA CLINICA", price: 238.00, description: "" },
  { id: "QUI-037", name: "PREALBUMINA", category: "QUIMICA CLINICA", price: 0.00, description: "" },
  { id: "QUI-038", name: "PROTEINAS TOTALES", category: "QUIMICA CLINICA", price: 148.00, description: "" },
  { id: "QUI-039", name: "SODIO", category: "QUIMICA CLINICA", price: 238.00, description: "" },
  { id: "QUI-040", name: "TAMIZ DE GLUCOSA CON CARGA", category: "QUIMICA CLINICA", price: 260.00, description: "" },
  { id: "QUI-009", name: "TGO", category: "QUIMICA CLINICA", price: 148.00, description: "" },
  { id: "QUI-010", name: "TGP", category: "QUIMICA CLINICA", price: 148.00, description: "" },
  { id: "QUI-006", name: "TRIGLICERIDOS", category: "QUIMICA CLINICA", price: 119.00, description: "" },
  { id: "QUI-008", name: "UREA", category: "QUIMICA CLINICA", price: 119.00, description: "" },
  { id: "QUI-041", name: "BUN", category: "QUIMICA CLINICA", price: 0.00, description: "" },
  { id: "QUI-042", name: "BI", category: "QUIMICA CLINICA", price: 0.00, description: "" },
  { id: "QUI-043", name: "VLDL", category: "QUIMICA CLINICA", price: 0.00, description: "" },
  { id: "URI-004", name: "ACIDO URICO URINARIO", category: "UROANALISIS", price: 55.00, description: "" },
  { id: "URI-005", name: "ACIDO URICO EN ORINA DE 24HR", category: "UROANALISIS", price: 150.00, description: "" },
  { id: "URI-006", name: "CALCIO URINARIO", category: "UROANALISIS", price: 75.00, description: "" },
  { id: "URI-007", name: "CREATININA URINARIA", category: "UROANALISIS", price: 55.00, description: "" },
  { id: "URI-008", name: "CREATININA URINARIA 24 HRS", category: "UROANALISIS", price: 140.00, description: "" },
  { id: "URI-009", name: "CRISTALOGRAFIA", category: "UROANALISIS", price: 0.00, description: "" },
  { id: "URI-010", name: "DEPURACION DE CREATININA", category: "UROANALISIS", price: 140.00, description: "" },
  { id: "URI-001", name: "EXAMEN GENERAL DE ORINA", category: "UROANALISIS", price: 111.00, description: "" },
  { id: "URI-011", name: "FOSFORO URINARIO", category: "UROANALISIS", price: 90.00, description: "" },
  { id: "URI-012", name: "GLUCOSA URINARIA", category: "UROANALISIS", price: 90.00, description: "" },
  { id: "URI-013", name: "MICRO ALBUMINA", category: "UROANALISIS", price: 320.00, description: "" },
  { id: "URI-014", name: "POTASIO URINARIO", category: "UROANALISIS", price: 110.00, description: "" },
  { id: "URI-015", name: "POTASIO URINARIO EN 24 HRS", category: "UROANALISIS", price: 120.00, description: "" },
  { id: "URI-003", name: "PROTEINA EN ORINA 24 HRS", category: "UROANALISIS", price: 148.00, description: "" },
  { id: "URI-016", name: "PROTEINA DE BENCE-JONES", category: "UROANALISIS", price: 0.00, description: "" },
  { id: "URI-017", name: "SODIO URINARIO", category: "UROANALISIS", price: 110.00, description: "" },
  { id: "URI-018", name: "UREA EN LIQUIDO DE DIALISIS", category: "UROANALISIS", price: 110.00, description: "" },
  { id: "URI-019", name: "UREA EN 24 HRS", category: "UROANALISIS", price: 221.00, description: "" },
  { id: "URI-020", name: "BUN URINARIO", category: "UROANALISIS", price: 0.00, description: "" },
  { id: "URI-021", name: "ANTIDOPING 3 ELEMENTOS", category: "UROANALISIS", price: 280.00, description: "" },
  { id: "URI-022", name: "ANTIDOPING 5 ELEMENTOS", category: "UROANALISIS", price: 477.00, description: "" },
  { id: "NUE-001", name: "AC PEPTIDOS CITRULINADOS", category: "NUEVOS ESTUDIOS", price: 1276.00, description: "" },
  { id: "NUE-002", name: "VITAMINA D", category: "NUEVOS ESTUDIOS", price: 900.00, description: "" },
  { id: "NUE-003", name: "ELECTROFORESIS DE LIPOPROTEINAS", category: "NUEVOS ESTUDIOS", price: 665.11, description: "" },
  { id: "NUE-004", name: "BETA 2 MICROGLOBULINA", category: "NUEVOS ESTUDIOS", price: 651.00, description: "" },
  { id: "NUE-005", name: "BANDAS OLIGOCLONALES", category: "NUEVOS ESTUDIOS", price: 1800.01, description: "" },
  { id: "NUE-006", name: "MICROALBUMINURIA EN ORINA 24 HRS", category: "NUEVOS ESTUDIOS", price: 490.97, description: "" },
  { id: "NUE-007", name: "SOMATOMEDINA C", category: "NUEVOS ESTUDIOS", price: 830.00, description: "" },
  { id: "NUE-008", name: "VITAMINA A", category: "NUEVOS ESTUDIOS", price: 2200.00, description: "" },
  { id: "NUE-009", name: "ELECTROFORESIS DE PROTEINAS EN ORINA 24 HRS", category: "NUEVOS ESTUDIOS", price: 1100.00, description: "" },
  { id: "NUE-010", name: "CERULOPLASMINA", category: "NUEVOS ESTUDIOS", price: 1125.00, description: "" },
  { id: "NUE-011", name: "AC. ANTI MITOCONDRIALES", category: "NUEVOS ESTUDIOS", price: 579.39, description: "" },
  { id: "NUE-012", name: "ANTI LKM", category: "NUEVOS ESTUDIOS", price: 1400.00, description: "" },
  { id: "NUE-013", name: "AC. ANTI MUSCULO LISO", category: "NUEVOS ESTUDIOS", price: 975.00, description: "" },
  { id: "NUE-014", name: "ALBUMINA EN ORINA DE 24 HORAS", category: "NUEVOS ESTUDIOS", price: 150.00, description: "" },
  { id: "NUE-015", name: "INMUNOFIJACIÓN", category: "NUEVOS ESTUDIOS", price: 2400.00, description: "" },
  { id: "NUE-016", name: "AC. VS VIRUS HEPATITIS A IGG E IGM", category: "NUEVOS ESTUDIOS", price: 509.27, description: "" },
  { id: "NUE-017", name: "TIROGLOBULINA", category: "NUEVOS ESTUDIOS", price: 1122.21, description: "" },
  { id: "NUE-018", name: "UREA EN ORINA", category: "NUEVOS ESTUDIOS", price: 174.00, description: "" },
  { id: "NUE-019", name: "AC. ANTI NUCLEARES", category: "NUEVOS ESTUDIOS", price: 481.51, description: "" },
  { id: "NUE-020", name: "FOSFOLIPIDOS IGG E IGM", category: "NUEVOS ESTUDIOS", price: 1461.60, description: "" },
  { id: "NUE-021", name: "TORCH 10 ELEMENTOS", category: "NUEVOS ESTUDIOS", price: 4152.80, description: "" },
  { id: "NUE-022", name: "AG. SARS CoV-2", category: "NUEVOS ESTUDIOS", price: 600.00, description: "" },
  { id: "NUE-023", name: "PRUEBA RAPIDA COVID IgG/IgM", category: "NUEVOS ESTUDIOS", price: 689.66, description: "" },
  { id: "NUE-024", name: "AC. IgG CUANTITATIVO", category: "NUEVOS ESTUDIOS", price: 950.00, description: "" },
  { id: "NUE-025", name: "PREALBUMINA", category: "NUEVOS ESTUDIOS", price: 578.00, description: "" },
  { id: "NUE-026", name: "OXCARBAZEPINA", category: "NUEVOS ESTUDIOS", price: 4393.99, description: "" },
  { id: "NUE-027", name: "LEVETIRACETAM", category: "NUEVOS ESTUDIOS", price: 3018.99, description: "" },
  { id: "NUE-028", name: "LAMOTRIGINA", category: "NUEVOS ESTUDIOS", price: 1644.00, description: "" },
  { id: "NUE-029", name: "AC ANTI-PEROXIDASA DE TIROIDES EN SUERO", category: "NUEVOS ESTUDIOS", price: 354.96, description: "" },
  { id: "NUE-030", name: "PCR-COVID", category: "NUEVOS ESTUDIOS", price: 3500.00, description: "" },
];

export default tests;